from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from agent_handoff.models import HandoffVerdict, RunResults, ScenarioResult


DEFAULT_TEMPLATE = """# Agent Handoff Acceptance Report

**Project:** {{project}}
**Overall verdict:** {{verdict}}

## Summary

{{summary}}

## Scenario results

{{scenario_table}}

## Layer coverage

Cross-layer baseline checks prompt, tool, memory, and retrieval behavior against golden fixtures before client sign-off.

## Sign-off

| Role | Name | Date | Signature |
| --- | --- | --- | --- |
| Delivery lead | | | |
| Client approver | | | |

---
Generated by [agent-handoff](https://github.com/mastroke/agent-handoff).
"""


def _scenario_rows(scenarios: list[ScenarioResult]) -> str:
    lines = ["| Scenario | Verdict | Failed layers |", "| --- | --- | --- |"]
    for scenario in scenarios:
        failed = ", ".join(layer.layer.value for layer in scenario.layers if not layer.passed)
        lines.append(
            f"| {scenario.name} | {'PASS' if scenario.passed else 'FAIL'} | {failed or '—'} |"
        )
    return "\n".join(lines)


def _summary(results: RunResults) -> str:
    total = len(results.scenarios)
    passed = sum(1 for scenario in results.scenarios if scenario.passed)
    if results.verdict == HandoffVerdict.PASS:
        return f"All {total} golden scenarios passed across prompt, tool, memory, and retrieval layers."
    return f"{passed}/{total} scenarios passed. Handoff blocked until failing layers are remediated."


def render_report(results: RunResults, template: str | None = None) -> str:
    body = template or DEFAULT_TEMPLATE
    return (
        body.replace("{{project}}", results.project)
        .replace("{{verdict}}", results.verdict.value)
        .replace("{{summary}}", _summary(results))
        .replace("{{scenario_table}}", _scenario_rows(results.scenarios))
    )


def load_results(path: Path) -> RunResults:
    data: dict[str, Any] = json.loads(path.read_text())
    from agent_handoff.models import Layer, LayerResult, ScenarioResult

    scenarios = []
    for raw in data.get("scenarios", []):
        layers = [
            LayerResult(
                layer=Layer(item["layer"]),
                passed=bool(item["passed"]),
                reason=str(item.get("reason", "")),
            )
            for item in raw.get("layers", [])
        ]
        scenarios.append(
            ScenarioResult(
                name=str(raw["name"]),
                description=str(raw.get("description", "")),
                layers=layers,
            )
        )
    return RunResults(project=str(data.get("project", "unknown")), scenarios=scenarios)


def load_template(path: Path | None) -> str | None:
    if path is None:
        return None
    return path.read_text()
